#!/usr/bin/env php
<?php
/**
 * @author Laurent Bachelier <laurent@bachelier.name>
 */


error_reporting(E_ALL|E_STRICT);

require_once __DIR__.'/autoload.php';

use Symfttpd\Command\ConfigurationGeneratorCommand;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$command = new \Symfttpd\Command\ConfigurationGeneratorCommand();
$command->run(new ArgvInput(), new ConsoleOutput());