#!/usr/bin/env php
<?php
/**
 * @author Laurent Bachelier <laurent@bachelier.name>
 */
require(dirname(__FILE__).'/lib/bootstrap.php');
require(dirname(__FILE__).'/lib/FileTools.php');
require(dirname(__FILE__).'/lib/MultiConfig.php');
require(dirname(__FILE__).'/lib/Application.php');
require(dirname(__FILE__).'/lib/Symfony1.php');
require(dirname(__FILE__).'/lib/Argument.php');
require(dirname(__FILE__).'/lib/Color.php');

/**
 * @pram string $project_path Absolute project path
 * @param string $target The destination of the symlink
 * @param string $link The relative path of the symlink to create
 * @param boolean $relative Try to use a relative destination
 * @return boolean Success
 *
 * @author Laurent Bachelier <laurent@bachelier.name>
 */
function replace_symlink($project_path, $target, $link, $relative = true)
{
  if ($relative)
  {
    $target = FileTools::calculateRelativeDir($project_path.'/'.$link, $target);
  }

  FileTools::mkdirs(dirname($project_path.'/'.$link));
  $success = FileTools::symlink($target, $project_path.'/'.$link);

  log_message('  '.$link.' => '.$target.($success ? '' : ' ...FAILED!'), !$success);
}


$options = MultiConfig::get();
$options['color'] = !Argument::get('C', 'no-color', false) && posix_isatty(STDOUT);
if ($options['color'])
{
  Color::enable();
}

$application = new Symfony1(Argument::get('P', 'path', null), $options['want']);
$project_path = $application->getProjectPath();

log_message(Color::style('bright') . Color::fgColor('green')
  . 'Using symfony version ' . Color::style('normal')
  . Color::fgColor('yellow') . $options['want'] . Color::style('normal'));

$symlinks = array();
if ($options['genconf'])
{
  $symlinks[$options['genconf']] = $options['path'].'/genconf';
}

$sf_path = $options['sf_path'][$options['want']];
foreach ($application->getAvailableLinks() as $option => $relpath)
{
  $link = $options[$option];
  if ($link)
  {
    $target = $sf_path.'/'.$relpath;
    if (!is_dir($target))
    {
      throw new Exception($target.' is not a directory');
    }
    $symlinks[$link] = $target;
  }
}

log_message(Color::style('bright') . Color::fgColor('green')
  . 'Creating required directories...' . Color::style('normal'));
FileTools::mkdirs($project_path.'/cache');
FileTools::mkdirs($project_path.'/log');

log_message(Color::style('bright') . Color::fgColor('green')
  . 'Creating symbolic links...' . Color::style('normal'));
foreach ($symlinks as $link => $target)
{
  replace_symlink($project_path, $target, $link, $options['relative']);
}
if ($options['do_plugins'])
{
  if (version_compare($options['want'], '1.2') >= 0)
  {
    log_message(Color::style('bright') . Color::fgColor('green')
      . 'Creating symbolic links for plugins... (calling symfony)'
      . Color::style('normal'));
    if (empty($options['php_cmd']))
    {
      $options['php_cmd'] = PosixTools::which('php');
    }
    system(trim($options['php_cmd'].' symfony plugin:publish-assets'));
  }
  else
  {
    log_message(Color::style('bright') . Color::fgColor('green')
      . 'Creating symbolic links for plugins... (internal method)'
      . Color::style('normal'));
    foreach ($application->findPlugins() as $name)
    {
      $link = 'web/'.$name;
      $target = $project_path.'/plugins/'.$name.'/web';
      // Ignore if there is a real directory with this name
      if (is_link($project_path.'/'.$link) || !is_dir($project_path.'/'.$link))
      {
        replace_symlink($project_path, $target, $link, $options['relative']);
      }
    }
  }
}
