#!/usr/bin/env php
<?php
/**
 * @author Laurent Bachelier <laurent@bachelier.name>
 * @author Benjamin Grandfond <benjamin.grandfond@gmail.com>
 */


require_once __DIR__.'/autoload.php';

use Symfttpd\Command\MksymlinksCommand;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

$command = new MksymlinksCommand();
$command->run(new ArgvInput(), new ConsoleOutput());