#!/usr/bin/env php
<?php
/**
 * @author Laurent Bachelier <laurent@bachelier.name>
 * @author Benjamin Grandfond <benjamin.grandfond@gmail.com>
 */


require_once __DIR__.'/autoload.php';

use Symfttpd\Command\MksymlinksCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\StringInput;

$app = new Application('Symfttpd');
$app->add(new MksymlinksCommand());
$app->run(new StringInput('mksymlinks'));