#!/usr/bin/env php
<?php
/**
 * @author Laurent Bachelier <laurent@bachelier.name>
 */
require dirname(__FILE__).'/lib/bootstrap.php';
require dirname(__FILE__).'/lib/Argument.php';
require dirname(__FILE__).'/lib/Template.php';
require dirname(__FILE__).'/lib/FileTools.php';
require dirname(__FILE__).'/lib/PosixTools.php';
require dirname(__FILE__).'/lib/MultiConfig.php';
require dirname(__FILE__).'/lib/Symfony.php';

$project_path = Symfony::getProjectPath();
$options = MultiConfig::get();

$options['port'] = intval(Argument::get('p', 'port', 4042));
$options['bind'] = Argument::get('A', 'all', false)
                 ? false
                 : Argument::get('b', 'bind', '127.0.0.1');
$options['project_path'] = $project_path;
$options['config_dir'] = $project_path.'/cache/lighttpd';
$options['log_dir'] = $project_path.'/log/lighttpd';
// hack: .sf files are not removed by symfony cc
$options['pidfile'] = $options['config_dir'].'/.sf';
$options['fork'] = !Argument::get('s', '--single-process', false);
if ($options['fork'] && !function_exists('pcntl_fork'))
{
  log_message('Warning: No fork() support.'
      . 'symfttpd will run in single-process mode.');
  $options['fork'] = false;
}

if (Argument::get('K', 'kill', false))
{
  if (file_exists($options['pidfile']))
  {
    $pid = intval(trim(file_get_contents($options['pidfile'])));
    unlink($options['pidfile']);
    if ($pid)
    {
      posix_kill($pid, SIGTERM);
      log_message('Process '.$pid.' killed');
      exit(0);
    }
  }
  log_message('No running process found', true);
  exit(1);
}

FileTools::mkdirs($options['config_dir']);
FileTools::mkdirs($options['log_dir']);

PosixTools::setCustomPath($options['custom_path']);
try
{
  if (empty($options['lighttpd_cmd']))
  {
    $options['lighttpd_cmd'] = PosixTools::which('lighttpd');
  }

  if (empty($options['php_cgi_cmd']))
  {
    $options['php_cgi_cmd'] = PosixTools::which('php-cgi');
  }

  if (empty($options['php_cmd']))
  {
    $options['php_cmd'] = PosixTools::which('php');
  }
}
catch (ExecutableNotFoundError $e)
{
  log_message("Required executable not found.", false);
  log_message($e->getMessage()
    . ' not found in the specified paths: '
    . implode(', ', PosixTools::getPaths()), false);
  exit(1);
}

$config_file = $options['config_dir'].'/lighttpd.conf';
file_put_contents(
  $config_file,
  Template::get($options['config_template'], $options)
);

// Pretty information. Nothing interesting code-wise.
log_message('lighttpd started on '
  . (strlen($options['bind']) ? $options['bind'] : 'all interfaces')
  . ', port '.$options['port'].'.');
log_message("\nAvailable applications");
$apps = array();
foreach (new DirectoryIterator($project_path.'/web') as $file)
{
  if ($file->isFile() && preg_match('/\.php$/', $file->getFilename()))
  {
    $apps[] = $file->getFilename();
  }
}
$host = in_array($options['bind'], array(false, '0.0.0.0', '::'), true)
      ? 'localhost'
      : $options['bind'];
sort($apps);
foreach ($apps as $app)
{
  log_message(' http://'.$host.':'.$options['port'].'/'.$app);
}
log_message("\nPress Ctrl+C to stop serving.");
flush();

passthru($options['lighttpd_cmd'].' -D -f '.escapeshellarg($config_file));

log_message('Terminated');
