#!/usr/bin/env php
<?php

require_once __DIR__.'/autoload.php';

use Symfttpd\Command\ConfigurationGeneratorCommand;
use Symfttpd\Command\MksymlinksCommand;
use Symfony\Component\Console\Application;

$application = new Application('symfttpd', '2.0.0');
$application->addCommands(array(
    new ConfigurationGeneratorCommand(),
    new MksymlinksCommand()
));
$application->run();