<?php
/**
 * This file is part of the Symfttpd Project
 *
 * (c) Laurent Bachelier <laurent@bachelier.name>
 * (c) Benjamin Grandfond <benjamin.grandfond@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 *
 * Default configuration options
 *
 * Do not edit this file!
 * Use the user-level config $HOME/.symfttpd.conf.php
 * and the project-level one at $PROJECT/config/symfttpd.conf.php
 *
 * @author Laurent Bachelier <laurent@bachelier.name>
 */

/**
 * Absolute path to the CGI PHP executable
 * @var string|boolean false to autodetect (try to find "php-cgi" in the path)
 */
$options['php_cgi_cmd'] = realpath(PHP_BINDIR.'/php-cgi');

// Required options
$options['project_type']    = 'php'; // Can be php or symfony
$options['project_version'] = null; // null only if type is php

// Not required options
$options['project_readable_dirs']     = null; // readable directories by the server in the web dir.
$options['project_readable_files']    = array('authors.txt', 'robots.txt'); // readable files by the server in the web dir (robots.txt).
$options['project_readable_phpfiles'] = null; // executable php files in the web directory
$options['project_readable_restrict'] = true; // if true the server will restrict access to other files than readable php files.
$options['project_nophp']             = array('uploads'); // deny PHP execution in the specified directories.
$options['project_log_dir']           = 'log';
$options['project_cache_dir']         = 'cache';
$options['project_web_dir']           = 'web';

// Required options
$options['server_type'] = 'lighttpd';

// Not required options
$options['server_cmd']         = null; // The server error log file of the server.
$options['server_pidfile']     = 'server_pidfile'; // The pidfile stores the PID of the server process.
$options['server_restartfile'] = 'server_restartfile'; // The file that tells the spawn command to restart the server.
$options['server_access_log']  = 'access.log'; // The server access log file of the server.
$options['server_error_log']   = 'error.log'; // The server error log file of the server.
